apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: logging
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: ash2code/flg-stack
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: logs
          mountPath: /var/log/app  # Ensure your application logs to this path
      volumes:
      - name: logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: logging
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
controlplane $ 
